import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Providers } from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";
import localfont from "next/font/local";

const kalam = localfont({
  src: "./Kalam-Variable.ttf",
  variable: "--font-kalam",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(kalam.className, "h-full overflow-x-hidden")}>
        <Toaster />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
